"""Markdown conformance report — human-readable, with an integrity stamp.

The report body is stamped with a SHA-256 digest so tampering is detectable. If
a signing key is supplied (``AGENTFENCE_SIGNING_KEY`` on the CLI), an
HMAC-SHA256 signature over the same body is appended — a zero-infrastructure way
to attest a report came from a trusted runner.
"""

from __future__ import annotations

import hashlib
import hmac

from agentfence import __version__
from agentfence.engine.models import ConformanceReport, ScenarioResult, Verdict

_VERDICT_LABEL = {
    Verdict.LEAK: "🔴 LEAK",
    Verdict.HELD: "🟢 HELD",
    Verdict.ASK: "🟡 ASK",
    Verdict.ERROR: "⚠️ ERROR",
    Verdict.SKIPPED: "⚪ SKIPPED",
}


def _summary_line(report: ConformanceReport) -> str:
    counts = report.summary_counts()
    parts = [f"{counts[v.value]} {v.value}" for v in Verdict if counts[v.value]]
    status = "PASS" if report.ok else "FAIL"
    return f"**{status}** — " + ", ".join(parts)


def _leak_section(result: ScenarioResult) -> str:
    action = result.attempt
    lines = [
        f"### {result.title} — `{result.boundary.value}`",
        "",
        f"- **Scenario:** `{result.scenario_id}`",
        f"- **Attempt:** `{action.tool}({action.value})`",
    ]
    if result.decision is not None:
        lines.append(f"- **Policy decision:** {result.decision.value.upper()}")
    if result.detail:
        lines.append(f"- **What happened:** {result.detail}")
    if result.citation:
        lines.append(f"- **Reference:** {result.citation}")
    lines.append("")
    return "\n".join(lines)


def _build_body(report: ConformanceReport) -> str:
    leaks = [r for r in report.results if r.verdict is Verdict.LEAK]
    asks = [r for r in report.results if r.verdict is Verdict.ASK]
    errors = [r for r in report.results if r.verdict is Verdict.ERROR]

    lines = [
        "# agentfence conformance report",
        "",
        f"- **Agent:** `{report.agent}` (models `{report.adapter_version}`)",
        f"- **Config:** `{report.config_source}`",
        f"- **Mode:** {report.mode}",
        f"- **Scenarios:** {report.total}",
        f"- **Result:** {_summary_line(report)}",
        "",
    ]

    if leaks:
        lines += ["## Leaks — boundaries that failed", ""]
        lines += [_leak_section(r) for r in leaks]
    else:
        lines += ["## Leaks", "", "None. Every tested boundary held. ✅", ""]

    if asks:
        lines += ["## Prompted (held only by a human gate)", ""]
        lines += [f"- `{r.scenario_id}` — {r.title} (`{r.boundary.value}`)" for r in asks]
        lines += [""]

    if errors:
        lines += ["## Errors", ""]
        lines += [f"- `{r.scenario_id}` — {r.detail}" for r in errors]
        lines += [""]

    lines += ["## All scenarios", "", "| Scenario | Boundary | Verdict |", "|---|---|---|"]
    for r in report.results:
        lines.append(f"| `{r.scenario_id}` | {r.boundary.value} | {_VERDICT_LABEL[r.verdict]} |")
    lines += [""]
    return "\n".join(lines)


def render_markdown(report: ConformanceReport, *, signing_key: str | None = None) -> str:
    """Render a signed Markdown conformance report."""
    body = _build_body(report)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    footer = [
        "---",
        "",
        f"_Generated by agentfence {__version__}._",
        f"_Integrity: `sha256:{digest}`_",
    ]
    if signing_key:
        signature = hmac.new(
            signing_key.encode("utf-8"), body.encode("utf-8"), hashlib.sha256
        ).hexdigest()
        footer.append(f"_Signature (HMAC-SHA256): `{signature}`_")
    return body + "\n" + "\n".join(footer) + "\n"
